### ISSUE TITLE
SeedTotem unable to use multiple matierials in custom JSON; missing counter increment?

### ISSUE THREAD

**Issue by DiskImage** [MathiasDecrock/ValheimMods#11]
I just did a bit more testing and narrowed the issue down to how you're parsing the JSON/using that JSON. If I only use an empty JSON object, 
`{}`
then the game loads fine, and I can build entirely free seed totems. If I add only a single key/val pair, that works, too.
```js﻿
{
"FineWood": 5
}
```

Using a second key/val pair caused the bug to happen:
```js﻿
﻿{
"FineWood": 5,
"GreydwarfEye": 5
}
```

https://github.com/MathiasDecrock/ValheimMods/blob/master/SeedTotem/SeedTotemPrefabConfig.cs#L75-L87

**Comment by MathiasDecrock** [comment]
Fixed in 1.1.5
