### ISSUE TITLE
SeedTotem Error in public test

### ISSUE THREAD

**Issue by xxxmailk** [MathiasDecrock/ValheimMods#21]
Console output error when I input seed into SeedTotem which is not working

[Error  : Unity Log] MissingMethodException: void Inventory.RemoveItem(string,int)
Stack trace:
Player.Interact (UnityEngine.GameObject go, System.Boolean hold, System.Boolean alt) (at <72a4973a1e0643c7be6461919c1a80dd>:0)
(wrapper dynamic-method) Player.DMD<Player::Update>(Player)

**Comment by mikeloeven** [comment]
Can confirm unable to add items to seed totem looks like this was broken in mistlands

**Comment by MathiasDecrock** [comment]
Sorry for my absence! 4.2.1 is released and seems to work without issues, just needed to update and recompile
